### ISSUE TITLE
Update Pekko dependancy version

### ISSUE THREAD

**Issue by iFairPlay22** [swagger-akka-http/swagger-pekko-http#1]
Hello,

Can you use one of the latest versions of Pekko in your build.sbt? If possible, could it be version 0.0.0+26621-44d03df6-SNAPSHOT?
If you do, do you need some help doing the changes?

Thank you for your time!

**Comment by pjfanning** [comment]
I don't see any benefit to this. Upgrade the dependency in your own build script.

**Comment by iFairPlay22** [comment]
I can not update my Pekko version. Indeed, if I update it and that I continue to use the latest version of swagger-pekko-http, my project will require 2 Pekko versions, that are not compatible. It will generate a binary compatibility error, as explained in this link: https://pekko.apache.org/docs/pekko/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed.

**Comment by iFairPlay22** [comment]
Yes, I agree, it deals with releases, but I have a mixed versioning issue in my project due to that, and I'm using snapshots... I will try to add some exclusions rules to resolve it then.

**Comment by pjfanning** [comment]
One way to workaround issues with testing with pekko snapshots is to set this config in your application.conf.
```
pekko.fail-mixed-versions = off
```
