### ISSUE TITLE
Update jackson dependency

### ISSUE THREAD

**Issue by VincentBrule** [swagger-akka-http/swagger-pekko-http#14]
Hello,

On the latest release, the jackson version is 2.15.2.
Since then, there is a new version (2.16.0) that was already updated in this repo bu not released yet.

This is causing issues when using this library because all our projects are using jackson 2.16.0 and we are getting this exception currently:
```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.15.2 requires Jackson Databind version >= 2.15.0 and < 2.16.0 - Found jackson-databind version 2.16.0
```

When do you plan to release a new stable version please?

Thanks

**Comment by pjfanning** [comment]
You can just update your own build dependencies - add explicit dependencies on all the jackson jars you need.
